### ISSUE TITLE
Абобус

### ISSUE THREAD

**Issue by Artemonchik** [nsu-null/null#23]
https://github.com/nsu-null/null/blob/b7c5927d276c640f8e568fcbcafaeed5a0fee572/src/NullGameEngine/SceneLoader.cpp#L51
Если расскоментить эту строчку, то мои остальные физические тела куда - то уезжают....

**Comment by Artemonchik** [comment]
Как будто https://github.com/nsu-null/null/blob/b7c5927d276c640f8e568fcbcafaeed5a0fee572/src/NullGameEngine/SceneLoader.cpp#L51 
если быть точнее
Тело которое умирает:
https://github.com/nsu-null/null/blob/b7c5927d276c640f8e568fcbcafaeed5a0fee572/src/NullGameEngine/SceneLoader.cpp#L85

**Comment by Artemonchik** [comment]
@p-vasilev здравствуйте, Роман, вы можете прокоментировать ситуацию? Вы с этим встречались?

**Comment by p-vasilev** [comment]
@Artemonchik `99.99%` проблема с скриптом камеры. Кажется, что камера и собственно фон поплыли относительно физ. мира. Я посмотрю, мб сделаю фикс.
Бтв, мемно (но возможно ненадолго):
https://github.com/nsu-null/null/blob/b7c5927d276c640f8e568fcbcafaeed5a0fee572/src/Scripts/ExampleCameraScript.cpp#L17

**Comment by Artemonchik** [comment]
@p-vasilev не могли бы вы влить изменение, которое это пофиксит, в эту ветку
