### ISSUE TITLE
is this some kind of pattern?

### ISSUE THREAD

**Issue by preciselyV** [nsu-null/null#43]
https://github.com/nsu-null/null/blob/48c4fda306bb5568e06a9f592a5d54ef5a57bf51/src/NullGameEngine/MainLoop.cpp#L104

**Comment by ghB111** [comment]
@preciselyV 
![image](https://user-images.githubusercontent.com/42515597/171986984-15b3c587-0f60-4a30-b6ae-a2b9f04a1895.png)

**Comment by Artemonchik** [comment]
Hello! Thank you for participating. We will fix this problem in NULL days and will send you email notification for review

**Comment by ghB111** [comment]
З̴̟́д̷̤̲̠͌ͅр̵͓̳̼̽͗̈́̚а̸̗̌̕в̴̼̑̽̿с̷͔͕̳̅͊т̶͔̝̾в̷̪̈́͊̽у̷̗̽й̶̛̫̻͔̞̇т̶̠̫̟̟̋͂͑е̴͕͝,̵͇̺̫̔ ̸̱̒̀͛͝в̸̼̘̲͆̿̊ы̸̞̩́͂ ̸͙͎̙̲́̏͐͠з̸̱̟̘̌а̷̨͛̍́б̴̮͍̂̎͝ы̶̥̑̽̏͠л̵̟͕̘͂̂͌и̵̢͍̓ ̵̢͙̫̩̾у̸̥͍͈͉͋к̶̨̹̬̜͐̎а̴̛͙̦͘з̷̢̇ͅа̶̺͉̤̄т̵̩͇̤̮͑ь̴̟̩͕̤̋ ̸̯̥̳̋͛͠с̵̹͔͋в̵̙͓̆̿͝о̷̡̠̫͆̇̀̃ю̸̜̥̬̦͗̿ ̷̨̖̈́̆̈͝о̴̥̿̀п̴̦̈́̑͌͝е̷̧͖͉́̄̓̕р̴̟̻͌͛̿̈́а̴̢̞̾̾́͜ц̴̢̊и̵̲̑͂͑̒о̸̜͖̇̕н̸̟̘̙̽̒н̴̺̱̥͉̂̌у̵͕̮͙͊͛ю̷̢͇͕͖̅̈́̕ ̷̙̾́͝с̶̤̉̽͛ͅи̷͍̯̬͇̍́͌́с̶̰̟̈́̃̆̃т̷͍̊͛̐̽͜е̸̯̗̅м̴͓̞͈͈̄͝у̵̡͛͒.̴̣͂̒

**Comment by hardworkar** [comment]
同事，但在投资者演示中，您宣布了您的游戏应用程序的跨平台性质??!!

**Comment by preciselyV** [comment]
это ноты ?

**Comment by ghB111** [comment]
там арабский с проклятыми утфными символами @preciselyV
